import jsPDF from 'jspdf'

type AgreementData = {
  ownerName: string
  ownerAddress: string
  tenantName: string
  tenantAddress: string
  propertyAddress: string
  monthlyRent: string
  securityDeposit: string
  startDate: string
  durationMonths: string
  noticePeriod: string
}

export function generateAgreementPdf(data: AgreementData) {
  const doc = new jsPDF()
  const margin = 20
  let y = 20
  const lineHeight = 7
  const pageWidth = doc.internal.pageSize.getWidth() - margin * 2

  const addText = (text: string, size = 10, bold = false) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    const lines = doc.splitTextToSize(text, pageWidth)
    doc.text(lines, margin, y)
    y += lineHeight * lines.length
  }

  const formattedDate = data.startDate
    ? new Date(data.startDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    : ''

  addText('RENTAL AGREEMENT', 16, true)
  y += 4

  addText(
    `This Rental Agreement is made on ${formattedDate} between:`,
    10
  )
  y += 2

  addText(`OWNER (Lessor): ${data.ownerName}`, 10, true)
  addText(`Address: ${data.ownerAddress}`, 10)
  y += 2

  addText(`TENANT (Lessee): ${data.tenantName}`, 10, true)
  addText(`Address: ${data.tenantAddress}`, 10)
  y += 4

  addText('1. PROPERTY', 11, true)
  addText(`The Owner agrees to rent out the property located at: ${data.propertyAddress}`)
  y += 2

  addText('2. RENT & DEPOSIT', 11, true)
  addText(`Monthly Rent: Rs. ${Number(data.monthlyRent).toLocaleString('en-IN')}`)
  addText(`Security Deposit: Rs. ${Number(data.securityDeposit).toLocaleString('en-IN')}`)
  addText('Rent shall be paid by the 5th of each month.')
  y += 2

  addText('3. TERM', 11, true)
  addText(`This agreement is valid for ${data.durationMonths} months, commencing from ${formattedDate}.`)
  y += 2

  addText('4. NOTICE PERIOD', 11, true)
  addText(`Either party must provide ${data.noticePeriod} month(s) written notice prior to termination.`)
  y += 2

  addText('5. GENERAL TERMS', 11, true)
  addText('The Tenant shall use the property only for residential purposes and shall not sublet without written consent from the Owner. The Tenant shall maintain the property in good condition and report any damages promptly.')
  y += 10

  addText('Signatures:', 10, true)
  y += 15
  addText('_______________________              _______________________')
  addText(`${data.ownerName} (Owner)                    ${data.tenantName} (Tenant)`)

  y += 15
  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text('This is a template document generated by HomeNex and does not constitute legal advice. Please consult a legal professional before signing.', margin, y, { maxWidth: pageWidth })

  doc.save(`Rental_Agreement_${data.tenantName.replace(/\s+/g, '_')}.pdf`)
}